package com.armando.SocialMedia.Model;

import java.sql.Timestamp;

/**
 * This is a class that models an Account.
 */
public class Account {
    public int account_id; // Automatically generated by the database
    public String username; // Must be unique and not blank
    public String password; // Must be at least 4 characters
    public Timestamp last_login; // New field: Tracks the last login time
    public Timestamp created_at; // New field: Tracks account creation time
    public Timestamp updated_at; // New field: Tracks the last update time

    // No-args constructor for Jackson ObjectMapper
    public Account() {}

    // Constructor for creating a new Account without timestamps
    public Account(String username, String password) {
        this.username = username;
        this.password = password;
    }

    // Constructor for creating an Account with account_id but no timestamps
    public Account(int account_id, String username, String password) {
        this.account_id = account_id;
        this.username = username;
        this.password = password;
    }


    // Constructor for retrieving an Account from the database with all fields
    public Account(int account_id, String username, String password, Timestamp last_login, Timestamp created_at, Timestamp updated_at) {
        this.account_id = account_id;
        this.username = username;
        this.password = password;
        this.last_login = last_login;
        this.created_at = created_at;
        this.updated_at = updated_at;
    }

    // Getters and Setters
    public int getAccount_id() {
        return account_id;
    }

    public void setAccount_id(int account_id) {
        this.account_id = account_id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Timestamp getLast_login() {
        return last_login;
    }

    public void setLast_login(Timestamp last_login) {
        this.last_login = last_login;
    }

    public Timestamp getCreated_at() {
        return created_at;
    }

    public void setCreated_at(Timestamp created_at) {
        this.created_at = created_at;
    }

    public Timestamp getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(Timestamp updated_at) {
        this.updated_at = updated_at;
    }

    // Overriding equals() method for comparison
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Account account = (Account) o;
        return account_id == account.account_id &&
                username.equals(account.username) &&
                password.equals(account.password) &&
                last_login.equals(account.last_login) &&
                created_at.equals(account.created_at) &&
                updated_at.equals(account.updated_at);
    }

    // Overriding toString() for debugging
    @Override
    public String toString() {
        return "Account{" +
                "account_id=" + account_id +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", last_login=" + last_login +
                ", created_at=" + created_at +
                ", updated_at=" + updated_at +
                '}';
    }
}
